name: MCEvolved
version: '${project.version}'
main: me.volt.main.mcevolved.MCEvolved
api-version: 1.20
authors: [ Volt ]
description: A plugin for the MCEvolved server.
website: https://github.com/voltywolty
