custom-items:
  hat_selector:
    name: "&bOpen Hat Menu"
    type: diamond_helmet
    hide-flags: true
    lore:
      - "§5§oClick to open the hat menu."
  santa_hat:
    name: "&cSanta §aHat"
    type: white_wool
    lore:
      - "§d(Click to Wear Hat)"

  game_list:
    name: "&6Game List"
    type: ink_sac